### PR TITLE
Adapting to JDK 9

### PR DESCRIPTION
**Pull request by YaSuenag**
For adapting to JDK 9, I've opened several issue on Bugzilla:
- [Bug 2911: [REFACTORING][JDK 9] Refactoring signal handling mechanism](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=2911)
- [Bug 2912: [JDK 9] Support JDK 9 version string](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=2912)
- [Bug 2913: [JDK 9] Adapt to JDK-8148047 ](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=2913)
- [Bug 2919: [JDK 9] Add Serial and Parallel GC hook for JDK 9](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=2919)
- [Bug 2923: [REFACTORING][JDK 9] Refactoring deadlock finder](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=2923)
- [Bug 2924: [JDK 9] Adapt to JEP 220](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=2924)

They work JDK 9 EA and Parallel GC (-XX:+UseParallelGC -XX:-UseParallelOldGC) ONLY.
Other GCs, we will work after JDK 9 Feature Complete.

Please review them!

### CODE REVIEW

**Comment by ykubota** [comment]
I take it to review. Please wait to double-check implementation of [jdk9/jdk9 (1985:51fb48619b0e)](http://hg.openjdk.java.net/jdk9/jdk9/rev/51fb48619b0e)

**Comment by ykubota** [comment]
Review to-do list:
- [x] jdk9 implementation
  - [x] share ([JDK-8148047](https://bugs.openjdk.java.net/browse/JDK-8148047), et al.)
  - [x] Serial / Parallel ([JDK-8075955](https://bugs.openjdk.java.net/browse/JDK-8075955), et al.)
  - [ ] ~~CMS~~ (do not support this gc now)
  - [ ] ~~G1~~ (do not support this gc now)
- [x] patch implementation
- [x] test to run ~~SPECjvm2008~~ TestCases

**Comment by YaSuenag** [comment]
@ykubota I DO NOT implement for CMS and G1 in JDK 9 yet.
We will work for it after JDK 9 FC.

If you run SpecJVM, you have to choose Parallel GC with `-XX:+UseParallelGC -XX:-UseParallelOldGC` .

**Comment by ykubota** [comment]
@YaSuenag OK, I skip to check these GCs.

**Comment by ykubota** [comment]
Sorry for late reply, I had faced some trouble when run SPECjvm with jdk9 because of java modularity.
Instead of SPECjvm, I confirmed there is no problem by running sample application which attached HeapStats (modified by this patches) with -XX:+UseParallelGC -XX:-UseParallelOldGC.

We need to test HeapStats with all garbage collectors by some benchmark when we finish making patch(es) for supporting JDK9 GA (or feature complete, final release candidate).

So now looks good to me, please push it.

**Comment by ykubota** [comment]
@YaSuenag 
Supporting jdk9 is experimental enhancement for HeapStats. So I think we should set label as future feature instead of setting milestone as 2.0.2.

In addition, this issue has several icedtea's bug id as first post. So we should merge it instead of rebase if you agree. Please remember to change ChangeLog after merging. :)

**Pull request merged**
