### PR TITLE
Bug 3194: Time-Awareness XAxis in FXAnalyzer

### PR DESCRIPTION
**Pull request by YaSuenag**
This PR is for [Bug 3194](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3194) .
Currently, all SnapShot data is drawn same distance:

before

After applying this patch, HeapStats user can be aware of time series:

after

Please review!

### CODE REVIEW

**Comment by ykubota** [comment]
Thank you for your good patch!
When we use time-awareness charts, steps on x-axis might be too much to confirm as your example.

**Comment by YaSuenag** [comment]
Do you say that we should remove all tick markers on X Axis? If so, should we fix it at first?

**Comment by ykubota** [comment]
Nope. IMHO, I think that we should remove a tick on x-axis when the number of steps is much than 50 (or more suitable number), if possible.

**Comment by YaSuenag** [comment]
I think tick marker on X Axis is not needed because we can check X value with popup window.

However, HeapStats Analyzer cannot show popup window on SnapShot summary window. I think we can implement it and remove all tick marker on another issue. What do you think about it?

**Comment by ykubota** [comment]
Good idea! I think that this idea might be better if we can select whether tick marker shows by property file.

I also think that a scale of X Axis is should be switchable instead of changing behavior.

**Comment by YaSuenag** [comment]
@ykubota Thank you for your comment.
I understand that your comment means we should change behavior for showing tick marker and for time-awareness X axis.

I will try to change them.

**Comment by YaSuenag** [comment]
@ykubota I've finished implementation of NumberAxis.
I've done to work for tick marker on #41 .
I've tried to implement CategoryAxis for compatibility, but I have a question. I want to hear your opinion.

This PR is implemented NumberAxis only. If we add CategoryAxis support, it makes complex.
CategoryAxis keeps String value for X axis. OTOH NumberAxis keeps Number value for it. So we have to comvert X values for drawing charts.

CategoryAxis does not have compatibility with NumberAxis.
In addition, I do not have any idea for it because FXAnalyzer is FXML application. So we cannot use class (controller class) inherits.

IMHO, HeapStats user do not want to use CategoryAxis after implementing this PR because it might make misreading.

According to implementation and usecase, I think we should not implement with CategoryAxis.
What do you think about them?

**Comment by ykubota** [comment]
@YaSuenag Sorry for late reply. I'm back.

NumberAxis is good idea to understand a heap situation correctly.

However, I cannot judge to drop the CategoryAxis out. I think some users still want to use the accustomed way. For example, I might count up a step of X-Axis by CategoryAxis at a glance to select the suitable snapshot of Java heap by the drop-down list of SnapShot Data Tab.

Although, I think that your opinion is also good for users. So, I want to make a suggestion that we implement the Summary Tab of CategoryAxis as a plugin (on anther issue).

**Comment by YaSuenag** [comment]
I want to merge this PR if I do not hear any objection until 8 Nov. JST .
Please review.

**Review by ykubota — APPROVED** [review]
LGTM. But we should wait to merge until 8 Nov. JST for hearing other comments.

**Comment by YaSuenag** [comment]
@ykubota BTW, can I merge this to 2.0 repos? Or should I merge to trunk only?
IMHO I want to merge this to trunk and 2.0 repos. However, it might be a big change. So I agree that this PR will be shipped in next major release if you want.

**Comment by ykubota** [comment]
@YaSuenag Please wait to merge to 2.0 repos until getting agreement our existing users.

**Comment by YaSuenag** [comment]
I merged this PR to development repos.
I've added TODO about merging 2.0 repos to [Projects](https://github.com/HeapStats/heapstats/projects) page.

**Pull request closed without merging**
