### PR TITLE
Bug 3356: [TEST]Add a race-condition test framework

### PR DESCRIPTION
**Pull request by ykubota**
HeapStats agent depends on HotSpot VM strongly. So HeapStats agent has potential dead lock and/or unexpected race conditions with an internal event of HotSpot VM.

We need to investigate these race condition by testing. First, we add a  framework for race condition test with HotSpot VM which enable to users to implement by python and gdb.

http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3356

### CODE REVIEW

**Review by YaSuenag — COMMENTED** [review]
Should you handle files at `agent/test/race-condition/ClassPrepare/` in Bug 3357 #92 ?
I guess this PR is for testing framework only.

**Comment by ykubota** [comment]
@YaSuenag 
This framework depends on a test case such as https://github.com/HeapStats/heapstats/pull/91/files#diff-335842c4e8c204204f3715ba057c111eR53
So I think that I should add an example test case for building and running this patch correctly.

Any thoughts?

**Comment by YaSuenag** [comment]
@ykubota Hmm... this framework can run (do nothing) if `testlist.txt` is empty. IMHO we should remove `ClassPrepare` and add empty `testlist.txt` for this change. What do you think?

**Comment by ykubota** [comment]
@YaSuenag 
OK, I will rebase both PRs.

**Comment by ykubota** [comment]
@YaSuenag I updated both PRs, please review again :)

**Review by YaSuenag — COMMENTED** [review]
Should we avoid to manage Python caches ( `.pyc` ) in the repository?

**Comment by ykubota** [comment]
Sure, I remove and ignore python bite-compiled files by reference to [github/gitignore](https://github.com/github/gitignore/blob/master/Python.gitignore)

**Review by YaSuenag — APPROVED** [review]

**Pull request closed without merging**
