### PR TITLE
Bug 3167: Fix incorrect message caused by class unloading in CMS.

### PR DESCRIPTION
**Pull request by YaSuenag**
This PR is for [Bug 3167](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3167).
Please review.

### CODE REVIEW

**Comment by ykubota** [comment]
We use a PR title as a commit message. So we should modify the title to tell what will this change do :)

Changes look good to me. But, what JDK version did you test with?

**Comment by YaSuenag** [comment]
Thank you Yuji! I changed the title of the ticket in IcedTea Bugzilla.

I've tested this fix with OracleJDK 7u80.

**Comment by ykubota** [comment]
Could you also test with JDK 8 just in case?

**Comment by YaSuenag** [comment]
@ykubota I checked this fix with OracleJDK 8u92 and JDK 9 EA b133 on Fedora 24 x86_64. They work fine.

**Comment by ykubota** [comment]
@YaSuenag 
:+1:  Okay, please merge it.

**Pull request closed without merging**
