### PR TITLE
Bug 3234: HeapStats agent cannot be upgraded with `rpm -U`

### PR DESCRIPTION
**Pull request by YaSuenag**
This PR is for [Bug 3234](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3234) .
Please review.

### CODE REVIEW

**Comment by ykubota** [comment]
Thanks for a report! Please wait until next Tuesday to test on RHEL 7.

**Review by ykubota — COMMENTED** [review]
Behavior is good. Please modify release.sh to delete the updating a version of cli package.

**Comment by YaSuenag** [comment]
Thanks Yuji!
I removed CLI version changes because my change uses `${version}` variable.

Please review again.

**Review by ykubota — APPROVED** [review]
Thank you for modifying.

**Pull request closed without merging**
