### PR TITLE
[WIP] Upload artifacts to the Maven Central Repository

### PR DESCRIPTION
**Pull request by ykubota**
We aim to upload artifacts to the Maven Central Repository for easy building and development.

Todo:
- [x] Update pom.xml to satisfy the [requirements](http://maven.apache.org/guides/mini/guide-central-repository-upload.html)
- [ ] Update pom.xml and/or codes to prepare [Javadoc and Sources Attachments](http://central.sonatype.org/pages/apache-maven.html#javadoc-and-sources-attachments)
- [ ] [GPG signed components](http://central.sonatype.org/pages/apache-maven.html#gpg-signed-components)
- [x] Sign up OSSRH JIRA (account name: ykubota)
- [ ] [Create issue on OSSRH JIRA](https://issues.sonatype.org/secure/CreateIssue.jspa?issuetype=21&pid=10134) to request for a creation of a maven repository for HeapStats.

Please wait to complete the above tasks.

### CODE REVIEW

**Comment by YaSuenag** [comment]
Thanks!
Should I review this PR after all tasks is done?
And will you upload all JARs to Maven Central? IMHO we should upload heapstats-core only. In addition, we should divide FXAnalyzer plugin API from heapstats-analyzer.jar and upload it to Maven Central.

**Comment by ykubota** [comment]
@YaSuenag 
Please review when I mention you before creating an issue on OSSRH JIRA.

IMHO, I should aim to upload heapstats-core by this issue at first. If we need to upload more packages, we should try it by other issues.

**Review by YaSuenag — COMMENTED** [review]
We change final name of heapstats-core in [here](https://github.com/HeapStats/heapstats/blob/master/analyzer/core/pom.xml#L66) . Should we change it?
I guess the libraries in Maven Central  should have version number in their file name.

**Comment by YaSuenag** [comment]
> IMHO, I should aim to upload heapstats-core by this issue at first. If we need to upload more packages, we should try it by other issues.

Okay, I remember it.

**Comment by YaSuenag** [comment]
@ykubota BTW, have you ever created a issue on [IcedTea Bugzilla](http://icedtea.classpath.org/bugzilla/) ?

**Comment by ykubota** [comment]
Ok, we agreed to upload heapstats-core only by this issue. So I booked at [icedtea bugzilla](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3219)

BTW, I will create a new issue on bugzilla if we need to separate commit for simple.

**Comment by ykubota** [comment]
Now, I close this PR temporary. I will reopen after finishing other tasks about test.

**Pull request closed without merging**
