### PR TITLE
Add the release change of heapstats-2.0.1

### PR DESCRIPTION
**Pull request by ykubota**
Add the following changes.
http://icedtea.classpath.org/hg/release/heapstats-2.0/rev/b244a7aae866

Note: I will not book this change for bugzilla.

### CODE REVIEW

**Comment by YaSuenag** [comment]
I think that you should push changes about configure.ac and release.sh only because this repository is trunk.

However, we have to decide trunk version number. IMHO, we can set 2.0-trunk or 0.0.0 as trunk version.
This version number change should be another commit.

What do you think about them?

**Comment by ykubota** [comment]
Agree.
Ok, I will write to fix the trunk version. Please wait a bit.

> IMHO, we can set 2.0-trunk or 0.0.0 as trunk version.

I think we should set 2.0.trunk. And release.sh does not support it. Because release.sh is not executable on trunk repository.
Any thoughts？

**Comment by YaSuenag** [comment]
If we migrate trunk repos to 2.1 or later, we have to change version number from 2.0.trunk .
I agree to your plan if you accept it.

**Comment by ykubota** [comment]
Sure.
I modify this patch to delete about versioning

**Comment by ykubota** [comment]
@YaSuenag Please check c489ed7

**Comment by YaSuenag** [comment]
Looks good!

**Comment by ykubota** [comment]
Thanks! I will merge this.

**Pull request closed without merging**
