### PR TITLE
Sync docs and config between icedtea and github

### PR DESCRIPTION
**Pull request by ykubota**
I will push .hgignore to icedtea for adding the below config.

``` bash
# github (git)
.git*
```

Any thoughts?

P.S.
I will push docs, i.e., README and CONTRIBUTING.md as well.

### CODE REVIEW

**Comment by YaSuenag** [comment]
I think .hgignore should not be ignored because it is managed by mercurial in IcedTea.

**Comment by YaSuenag** [comment]
You should add .gitignore to IcedTea mercurial.
And you should add .git to .hgignore .

**Comment by ykubota** [comment]
Thanks comment!

I think that maintainer try not to let the developers who use git bother about mercurial.
Even if .{hg|git}ignore ignore each other, maintainer can push it without affecting both.

**Comment by ykubota** [comment]
Setting example for maintainer

``` zsh
/workspace/heapstats% tree -L 1 -a
.
|-- .git
|-- .gitignore
|-- .hg
|-- .hgignore
|-- .hgtags
|-- AUTHORS
|-- CONTRIBUTING.md
|-- COPYING
|-- ChangeLog
|-- INSTALL
|-- Makefile.am
|-- Makefile.in
|-- NEWS
|-- README
|-- README.md -> README
|-- aclocal.m4
|-- agent
|-- analyzer
|-- configure
|-- configure.ac
|-- m4
|-- mbean
|-- pom.xml
\-- specs

7 directories, 17 files
/workspace/heapstats% hg status
M .hgignore
M README
A CONTRIBUTING.md
/workspace/heapstats% git status
On branch sync_configs
Your branch is up-to-date with 'origin/sync_configs'.
nothing to commit, working directory clean
```

**Comment by YaSuenag** [comment]
I think .hgignore and .gitignore should be managed by SCM.
As you say, Git user(s) does not need to modify .hgignore . However, we should synchronze them each other.

Currently, we manage same trunk source code at GitHub and IcedTea HG, and we should synchronize them each other. ignore files are managed at both SCM as material.
Thus I think all materials should be managed both SCM.

If we update ignore entry, we have to update both files and they are should be managed.
(I will send PR to add heapstats-cli shell to each ignore file.)

**Comment by ykubota** [comment]
OK, your thought looks reasonable to me. 

Shall we create a symbolic link for .{git,hg}ignore ?
- Pros
  - We change only 1 file when we need to change.
- Cons
  - We need to track .hgtags, too.

**Comment by YaSuenag** [comment]
Okay if it is possible.
However, it might be different syntax.

For example, target directories in analyzer are NOT ignored at Git. HG ignores them. You have to check git status after build all make target.

**Comment by ykubota** [comment]
Good point! I create a symbolic link, .ignore, and update it to fill a gap between hg and git.
Please check it.
- the result of status after `./configure; make all`

``` bash
/workspace/heapstats% git status
On branch sync_configs
Your branch is up-to-date with 'origin/sync_configs'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        typechange: .gitignore
        new file:   .hgignore
        new file:   .hgtags
        copied:     .gitignore -> .ignore

/workspace/heapstats% hg status
M .hgignore
M README
A .gitignore
A .ignore
A CONTRIBUTING.md
```
- tree of analyzer (after `./configure; make all`)

``` bash
/workspace/heapstats% tree analyzer/ -L 3
analyzer/
|-- cli
|   |-- heapstats-cli
|   |-- heapstats-cli.in
|   |-- pom.xml
|   |-- src
|   |   `-- main
|   `-- target
|       |-- archive-tmp
|       |-- classes
|       |-- generated-sources
|       |-- heapstats-cli-2.0-bin
|       |-- heapstats-cli-2.0-bin.zip
|       |-- heapstats-cli.jar
|       |-- maven-archiver
|       `-- maven-status
|-- core
|   |-- pom.xml
|   |-- src
|   |   `-- main
|   `-- target
|       |-- classes
|       |-- generated-sources
|       |-- heapstats-core.jar
|       |-- maven-archiver
|       `-- maven-status
`-- fx
    |-- THIRD_PARTY_README
    |-- filterDefine.xsd
    |-- heapstats.properties
    |-- lib
    |   `-- jgraphx.jar
    |-- nbactions.xml
    |-- pom.xml
    |-- src
    |   `-- main
    `-- target
        |-- archive-tmp
        |-- classes
        |-- generated-sources
        |-- heapstats-analyzer-2.0-bin
        |-- heapstats-analyzer-2.0-bin.zip
        |-- heapstats-analyzer.jar
        |-- maven-archiver
        `-- maven-status

29 directories, 15 files
```

**Comment by YaSuenag** [comment]
Good! You can merge it!

**Comment by ykubota** [comment]
Thank for reviewing !

I will [merge to here and icedtea](https://github.com/HeapStats/heapstats/wiki/Maintenance-and-sync-policy-with-mercurial-icedtea#merge-from-topic-branches) :-)

**Pull request closed without merging**
