### PR TITLE
Bug 3752: Migrate to OpenJFX 13

### PR DESCRIPTION
**Pull request by YaSuenag**
This PR is for [Bug 3752](https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3752).

Currently HeapStats Analyzer ships as standalone JavaFX application, so the user needs to install JavaFX runtime.
However recently Java does not include JavaFX, so it is inconvinience.

I think it is very useful if HeapStats Analyzer ships with JavaFX runtime. One solution is jlink with OpenJFX.
We need to work as below for it:

* Modularization
* Up to JDK 7 in some modules
* Migrate to OpenJFX 13

### CODE REVIEW

**Comment by ykubota** [comment]
Let me make sure one thing at the beginning, do you consider to drop supporting older than Java 11 for analyzer?
https://github.com/HeapStats/heapstats/pull/144/files#diff-97af00cde5d14c97738498b604c2f5a3R75

**Comment by ykubota** [comment]
why not drop Java 7 as well :p
https://github.com/HeapStats/heapstats/pull/144/commits/d63a80988f4dff89dcac0f61957acd9de0059036#diff-45bd6e70c252d1e19e416f335b568c10R30

**Comment by YaSuenag** [comment]
For using `jlink`, we need to modularize HeapStats Analyzer and related modules. So I up the version to 11.

For Agent attacher and HeapStats MBean, they are not included in HeapStats Analyzer. But they will be built with JDK 13 because this PR uses `jlink` in JDK 13. So we need to source version / target version to 7 due to `javac` restriction.

**Comment by ykubota** [comment]
How about consider to release 2.2.0 instead of 2.1.2 because this change drops older Java supporting. In addition, I wanna suggest dropping Java 7 as well.

**Comment by YaSuenag** [comment]
I retargetted this PR to 2.2 .

**Review by ykubota — COMMENTED** [review]
Please update README to describe the Java version each component supports and how to build individually. Others look good to me.

Nit: copyright year of pom.xml : https://github.com/HeapStats/heapstats/blob/216946d2f81de31ca75237232acb364ccad918ee/analyzer/cli/pom.xml#L4

**Comment by YaSuenag** [comment]
I updated copyright year in all modified files.

I think we should work for README.md on another ticket because current description is not enogh.  
What do you think?

**Review by ykubota — APPROVED** [review]
LGTM.

And Okay to update README by another ticket.

**Comment by YaSuenag** [comment]
@ykubota Thanks!

I filed README updates as [Bug 3753](https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3753) and I will work for it.

**Pull request closed without merging**
