### PR TITLE
[WIP]CategoryAxis and NumberAxis integration

### PR DESCRIPTION
**Pull request by YaSuenag**
THIS PR IS NOT JUST A PULL-REQUEST! I WANT TO START TO DISCUSS FROM THIS PR!!

I've working for migration to NumberAxis to draw time-awareness charts in [Bug 3194](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3194) and PR #40 .
I've heard the comment that we should continue to provide CategoryAxis version because some users still want to use the accustomed way.

I implemented CategoryAxis and NumberAxis on charts on Log Resource tab. You can select `x_numberaxis` in `heapstats.conf` . If you set it to `true`, all charts in Log Resource tab will be drawn with `NumberAxis` . Otherwise, they will be drawn with `CategoryAxis` .

However, I cannot implement it to SnapShot tab and cannot move forward this PR.
I guess this implementation is too complex.

For example, we have to remove definitions about all XYCharts from FXML, and we need to add custom `ControllerFactory` . I added base class for drawing charts and two sub class for special processing of `NumberAxis` and `CategoryAxis` . I'm not certain this is right. If this PR is too complex and difficult to maintainance, I will propose `NumberAxis` only version (it means #40 ).

Before implementing it for SnapShot tab, I want to discuss.
Please help!!

### CODE REVIEW

**Comment by ykubota** [comment]
If there are not any objections and comments, we should merge #40 only.

**Comment by YaSuenag** [comment]
@ykubota What do you think about this PR? Should we move forward this PR?

**Comment by ykubota** [comment]
@YaSuenag Yes. I agree with your opinion because there are no objections by other people for a past week.

**Comment by YaSuenag** [comment]
I will close this PR without merging if we do not hear any opinions for this after merging #40 .

**Comment by YaSuenag** [comment]
#40 has been merged. So I close this PR.

**Pull request closed without merging**
