### PR TITLE
Bug 3261: Cannot start FXAnalyzer when HeapStatsFXAnalyzer.main() is called directly

### PR DESCRIPTION
**Pull request by YaSuenag**
This PR is for [Bug 3261](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3261).
Please review it.

### CODE REVIEW

**Comment by ykubota** [comment]
@YaSuenag IMO, I think that we don't run the main class directly, so we need this PR for IDE support. Thus this PR should be labeled as an enhancement. Any thoughts?

**Comment by YaSuenag** [comment]
In general, any Java classes which has entry point ('main' method) might be called directly (not `java -jar`). So I marked this to bug.

**Comment by ykubota** [comment]
@YaSuenag OK, I concur with you. 
(I only thought that we should describe what difference about other IDE support issues. :) )

**Review by ykubota — APPROVED** [review]
Memo: This change has small refactoring to fix indents.

**Pull request closed without merging**
