### PR TITLE
Bug 3250: Collect safepoint time when SnapShot is collected

### PR DESCRIPTION
**Pull request by YaSuenag**
This PR is for [Bug 3250](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3250).
Please review it.

### CODE REVIEW

**Comment by ykubota** [comment]
This change will make SnapShot includes new information "safepoint time" which is very useful for analysis about "OutOfMemoryError: GC overhead limit exceeded".

Does this change have a breaking change such as older versions snapshot cannot load by analyzer?

**Comment by YaSuenag** [comment]
@ykubota Yes, SnapShot after this change cannot be loaded by older Analyzer.
Should not I merge this to 2.0 branch?

Of course, older SnapShot can be loaded by newer Analyzer.

**Comment by ykubota** [comment]
@YaSuenag If this change has backward compatibility, this is *NOT* a breaking change. So we should merge this change to 2.0 repository.

**Review by ykubota — APPROVED** [review]
If you agree, please change a commit message for understanding that this patch adds a new runtime information into SnapShot. 

E.g.)
 * Add safepoint time into SnapShot
 * Make SnapShot includes safepoint time

**Pull request closed without merging**
